### ISSUE TITLE
请教大佬一个问题，加入黑名单的广告域名屏蔽不掉

### ISSUE THREAD

**Issue by guitoushayan** [Goooler/1024_hosts#2]
https://www.66s.cc/我把这个网页上的广告域名加入了黑名单了，但是还有显示是为什么？

**Comment by Goooler** [comment]
你抓包看一下域名被拦截掉了没有，或者先清一下浏览器缓存

guitoushayan <notifications@github.com> 于 2020年5月9日周六 22:46写道：

**Comment by guitoushayan** [comment]
抓包不会啊，浏览器缓存清理过了,我右键广告复制链接地址是这个www.yumi1.club，www.9tjoh.info,www.0rtidh.info,zzg.e8xr.com大佬能帮忙加入到您的hosts中吗？我查看了下，您那个里面没有这个

**Comment by Goooler** [comment]
白天忙，忘记了，马上看看

**Comment by Goooler** [comment]
> 抓包不会啊，浏览器缓存清理过了,我右键广告复制链接地址是这个www.yumi1.club，www.9tjoh.info,www.0rtidh.info,zzg.e8xr.com大佬能帮忙加入到您的hosts中吗？我查看了下，您那个里面没有这个

处理好了，你试试看

**Comment by guitoushayan** [comment]
感谢大佬，广告没有了

**Comment by Goooler** [comment]
> 感谢大佬，广告没有了

不给个赞吗（手动斜眼）

**Comment by guitoushayan** [comment]
疏忽了，疏忽了
