### ISSUE TITLE
腾讯的几个网址误杀

### ISSUE THREAD

**Issue by ihuaer** [Goooler/1024_hosts#4]
![photo_2020-10-28_23-04-18](https://user-images.githubusercontent.com/12723080/97518609-8a5b5500-19d2-11eb-934f-95b3d33699f9.jpg)
这几个网址屏蔽后，微信都不能下载
https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe

**Comment by Goooler** [comment]
> ![photo_2020-10-28_23-04-18](https://user-images.githubusercontent.com/12723080/97518609-8a5b5500-19d2-11eb-934f-95b3d33699f9.jpg)
> 这几个网址屏蔽后，微信都不能下载
> https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe

已修改提交
